// IF WE KNOW KEY IN ADVANCE WE CAN DO PERFECT HASHING

// IF WE DO NOT KNOW KEYS THEN WE USE ONE OF THE FOLLOWING

// --> CHAINING
// --> OPEN ADDRESSING 
        // --> LINEAR PROBLING
        // --> QUADRATIC PROBING 
        // --> DOUBLE HASHING

